# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "910ed59f4c898ed034b4f8be05b8ed58"
name = "product-customization-simple"
application_url = "https://shopify-test-app-y90x.onrender.com/"
embedded = true

[build]
automatically_update_urls_on_dev = false

[webhooks]
api_version = "2025-10"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products,read_products"

[auth]
redirect_urls = [
  "https://shopify-test-app-y90x.onrender.com/api/auth",
  "https://shopify-test-app-y90x.onrender.com/api/auth/callback"
]

